title: COMP251
description: "COMP251: Systems Programming"
url: https://comp251-sp23-jtd.github.io
theme: just-the-docs
color_scheme: light

callouts:
  important:
    title: Important
    color: blue
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple
  new:
    title: New
    color: green
  announcement:
    title: Announcement
    color: blue

collections:
  homework:
    output: true
  labs:
    output: true

just_the_docs:
  collections:
    homework: 
      name: Assignments
        #nav_fold: true
    labs:
      name: Labs
        #nav_fold: true

mermaid:
  version: "9.1.3"

kramdown:
  parse_block_html: true

heading_anchors: true

search_enabled: true

permalink: pretty

nav_external_links:
  - title: Code from Class
    url: https://github.com/comp251/code-from-class
  - title: Slack
    url: https://rhodes-cs.slack.com
  - title: Feedback
    url: https://forms.gle/74oBX4KXSBuonmvh8


aux_links:
  Marion Lang: https://ml8.github.io
