title: COMP251
description: "COMP251: Systems Programming"
url: https://comp251.github.io
theme: just-the-docs
color_scheme: light

callouts:
  important:
    title: Important
    color: blue
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple
  new:
    title: New
    color: green
  announcement:
    title: Announcement
    color: blue

collections:
  homework:
    output: true
  labs:
    output: true

just_the_docs:
  collections:
    homework: 
      name: Assignments
        #nav_fold: true
    labs:
      name: Labs
        #nav_fold: true

mermaid:
  version: "9.1.3"

kramdown:
  parse_block_html: true

heading_anchors: true

search_enabled: true

permalink: pretty

footer_content: "Copyright &copy; 2022-2023 Marion Lang."

last_edit_timestamp: false
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: true 
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/comp251/comp251.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

nav_external_links:
  - title: Code from Class
    url: https://github.com/comp251/code-from-class
  - title: Slack
    url: https://rhodes-cs.slack.com
  - title: Feedback
    url: https://tinyr.us/lang-feedback


aux_links:
  Marion Lang: https://ml8.github.io
