title: COMP251
description: "COMP251: Systems Programming"
theme: just-the-docs

url: https://comp251-sp23-jtd.github.io

color_scheme: light

callouts:
  important:
    title: Important
    color: blue
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple
  new:
    title: New
    color: green
  announcement:
    title: Announcement
    color: blue

collections:
  homework:
    output: true
  labs:
    output: true

just_the_docs:
  collections:
    homework: 
      name: Assignments
        #nav_fold: true
    labs:
      name: Labs
        #nav_fold: true

mermaid:
  version: "9.1.3"

heading_anchors: true

aux_links:
  Marion Lang: https://ml8.github.io
